### ISSUE TITLE
cannot find base module

### ISSUE THREAD

**Issue by ghost** [simplabs/ember-cli-simple-auth-torii#19]
I am getting this error:

```
Uncaught Error: Could not find module `simple-auth/authenticators/base` imported from `simple-auth-torii/authenticators/torii`
```

could this be related to https://github.com/simplabs/ember-cli-simple-auth/issues/42?

**Comment by marcoow** [comment]
If you're using Ember Simple Auth 1.x you don't need this package anymore as all the functionality is already included in the main ember-simple-auth package now.

**Comment by ghost** [comment]
Thank you for clarifying!
